builder:
  track: dev

labels:
  app: estafette-extension-github-status
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

stages:
  build:
    image: golang:1.10.2-alpine3.7
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: extensions/docker:dev
    action: build
    container: github-status
    repositories:
    - extensions
    path: ./publish
    copy:
    - Dockerfile

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: github-status
    repositories:
    - extensions
    tags:
    - dev

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(fI3-FVVuCISewUB7.us1witAljV1RkjZ23G17KVLzBBzfwT0mJ24ORfjAFs7aJElUy9iQ_9nvO5CQnBG8WgT5YQ5l4N6c3vLZTc3zKDZ8fhfBWWLhwzP6Tdfvy8Jd5Y-8xVqeA5sgni4_)
    name: ${ESTAFETTE_LABEL_APP}
    channels:
    - '#build-status'
    when:
      status == 'failed'

releases:
  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: github-status
        repositories:
        - extensions
        tags:
        - beta

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: github-status
        repositories:
        - extensions
        tags:
        - stable
        - latest